ERROR:Sem15_Task3:Ошибка division by zero в функции func_2 при аргументах (5, 0), {}
ERROR:Sem15_Task3:Ошибка 'a' в функции my_func при аргументах ({'f': '1', 'd': '3', 's': '5'}, 'a', 2), {}
ERROR:Sem15_Task3:Ошибка  в функции print_date при аргументах ('1-й четверг ноября',), {}
